'use client';
import { useEffect, useState } from 'react';
import { DashboardShell } from '../../../components/dashboard-shell';
import { CheckCircle2, Link2, Save, ShieldCheck } from 'lucide-react';
import { toast, Toaster } from 'sonner';
export default function Settings() {
  const [token, setToken] = useState(''); const [maskedToken, setMaskedToken] = useState<string | null>(null); const [maxChannels, setMaxChannels] = useState('3'); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState(false);
  useEffect(() => { fetch('/api/settings').then(r => r.json()).then(data => { if (data.token) setMaskedToken(data.token); if (data.max_channels_per_post) setMaxChannels(String(data.max_channels_per_post)); }).catch(() => toast.error('Unable to load settings')); }, []);
  async function save() { if (!token.trim()) { toast.error('Enter a new bot token before saving'); return; } setSaving(true); try { const res = await fetch('/api/settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ telegram_bot_token: token, max_channels_per_post: Number(maxChannels) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setMaskedToken(data.token); setToken(''); toast.success(`Connected as @${data.bot.username}`); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save bot token'); } finally { setSaving(false); } }
  async function test() { setTesting(true); try { const res = await fetch('/api/settings'); const data = await res.json(); if (!res.ok || !data.configured) throw new Error('No bot token is configured'); toast.success(`Bot token configured: ${data.token}`); } catch (error) { toast.error(error instanceof Error ? error.message : 'Bot test failed'); } finally { setTesting(false); } }
  return <DashboardShell><Toaster theme="dark"/><div className="topline"><div><div className="eyebrow">System / configuration</div><h1 className="h1">Settings</h1><div className="muted" style={{ fontSize: 13, marginTop: 7 }}>Credentials are stored server-side in Supabase and never returned in full.</div></div><button className="btn primary" onClick={save} disabled={saving}><Save size={14}/>{saving ? 'Saving…' : 'Save changes'}</button></div><div className="grid grid2"><div className="card"><div className="eyebrow">Telegram bot</div><h2 style={{ fontSize: 18, margin: '5px 0 20px' }}>Connection</h2><label className="label">Bot token {maskedToken && <span className="green">· configured as {maskedToken}</span>}</label><input className="input" type="password" placeholder={maskedToken ? 'Enter a new token to replace it' : '123456789:AA…'} value={token} onChange={event => setToken(event.target.value)} autoComplete="off"/><div style={{ display: 'flex', gap: 8, marginTop: 15 }}><button className="btn" onClick={test} disabled={testing}><CheckCircle2 size={13} className="green"/> {testing ? 'Testing…' : 'Test saved token'}</button><button className="btn primary" onClick={() => toast.info('Webhook endpoint: /api/telegram/webhook')}><Link2 size={13}/> Connect webhook</button></div><div className="notice" style={{ marginTop: 15 }}>Saving validates the token with Telegram <span className="mono">getMe</span> first, then writes it to <span className="mono">app_settings</span>.</div></div><div className="card"><div className="eyebrow">Distribution rules</div><h2 style={{ fontSize: 18, margin: '5px 0 20px' }}>Guardrails</h2><label className="label">Maximum destination channels per post</label><input className="input" type="number" min="1" max="20" value={maxChannels} onChange={event => setMaxChannels(event.target.value)}/><div className="notice" style={{ marginTop: 15 }}><ShieldCheck size={15} className="green" style={{ verticalAlign: 'middle', marginRight: 7 }}/>Forwarded mode is automatically disabled for manually drafted posts.</div></div></div></DashboardShell>
}
